# template.py

instruction="""
;; This file is autogenerated from Haqiba(sachin.pythonanywhere.com).
;; Rename THIS file to .emacs and copy to your $HOME path(~).
;; Or you can test this config file using the command
;; 'emacs -q -l emacs_init.el'
"""
